<h1>List of files</h1>
<div>
	<?php
	foreach ($this->files as $value) {
	?>
	<div style="float: left;margin : 10px;">
		<a href ="<?php echo $this->url(array('action'=>'get','file-id'=>$value['id']))?>">
			<?php echo $value['filename']?>
		</a>
		<br />
		<a href ="<?php echo $this->url(array('action'=>'delete','file-id'=>$value['id'],'version'=>$value['version']))?>">
			Delete image
		</a>
		&nbsp;|&nbsp;
		<a href ="<?php echo $this->url(array('action'=>'get-meta','file-id'=>$value['id']))?>">
			View Meta
		</a>
		
	</div>
	<?php } ?>
</div>
<div style='clear: both;'></div>
<h1>File upload</h1>

<form method="post" action="<?php echo $this->url(array('action' => 'put')); ?>" enctype="multipart/form-data">
	<input name='uploadfile' type="file"/>
	<br />
	<input type="submit" name="submit" value="upload"/>
</form>