<!DOCTYPE html>

<html lang="fr">
<head>
  <meta charset="UTF-8">

  <title>Connexion</title>

  <link rel="stylesheet" media="screen" href="<?php echo $this->baseUrl();?>/css/style.css">
</head>
<body>
    
	<div id="login">
		<h1 class="title1">Bienvenue sur le back-office de Rubedo</h1>
		<form method="post" action="/backoffice/xhr-authentication/login" >
			Login : <input type="text" name="login" class="input" /><br />
			Password : <input type="password" name="password" class="input" /><br />
			<input type="submit" value="Connexion" class="button" />
			<?php
				if(isset($_GET['error'])){
					$msg = $_GET['error'];
					if($msg == "badLogin"){
						echo "<div class=\"error\">Identifiants incorrects !</div>";
					}
				}
			?>
		</form>
	</div>

</body>
</html>