<!DOCTYPE html>
<html ng-app="rubedo" ng-controller="RubedoController as rubedo">
<head>
    <meta charset="UTF-8">
    <!--mobile meta-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title ng-bind-template="{{rubedo.current.page.text}}"></title>
    <!--css-->
    <link rel="stylesheet" href="/components/twbs/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/components/webtales/rubedo-frontoffice/css/rubedo.css">
    <!--library scripts-->
    <script src="/components/jquery/jquery/jquery-1.10.1.min.js"></script>
    <script src="/components/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/components/angular/angular.js/angular.js"></script>
    <script src="/components/angular/angular.js/angular-route.js"></script>
    <script src="/components/lodash/lodash/dist/lodash.min.js"></script>
    <script src="/components/mgonto/restangular/dist/restangular.js"></script>
    <!--frontoffice scripts-->
    <script src="/components/webtales/rubedo-frontoffice/src/modules/rubedoDataAccess/rubedoDataAccess.js"></script>
    <script src="/components/webtales/rubedo-frontoffice/src/modules/rubedoBlocks/rubedoBlocks.js"></script>
    <script src="/components/webtales/rubedo-frontoffice/src/modules/rubedo/rubedo.js"></script>
    <!--base href for angular routing-->
    <base href="/">
</head>
<body>
<div ng-view></div>
</body>
</html>