<!DOCTYPE html>
<html xmlns:ng="http://angularjs.org" id="ng-app" ng-app="rubedo" ng-controller="RubedoController as rubedo">
<head>
    <!--[if lte IE 8]>
    <script>
        document.createElement('ng-include');
        document.createElement('ng-repeat');
        document.createElement('ng-view');
        document.createElement('rubedo-block');
        document.createElement('rubedo-field');
        document.createElement('rubedo-notification');
        document.createElement('snap-drawer');
        document.createElement('snap-content');
        document.createElement('rubedo-custom-template');
    </script>
    <![endif]-->
    <meta charset="UTF-8">
    <!--mobile meta-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title ng-bind-template="{{rubedo.current.page.text}}"></title>
    <!--css-->
    <link rel="stylesheet" href="/components/jtrussell/angular-snap.js-bower/angular-snap.min.css">
    <link rel="stylesheet" href="/components/twbs/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/components/webtales/rubedo-frontoffice/css/rubedo.css">
    <link href='/components/jquery/fullcalendar/fullcalendar.css' rel='stylesheet' />
    <link href='/components/jquery/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
    <link rel="stylesheet" href="/components/OwlFonk/OwlCarousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="/components/OwlFonk/OwlCarousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="/components/vitalets/angular-xeditable/dist/css/xeditable.css">
    <!--external resource styles-->
    <?php foreach ($this->siteResources['externalStyles'] as $externalStyle): ?>
        <link rel="stylesheet" href="<?php echo $externalStyle['url']; ?>">
    <?php endforeach; ?>
    <!--internal resource styles-->
    <?php foreach ($this->siteResources['internalStyles'] as $internalStyle): ?>
        <?php if (is_array($internalStyle)): ?>
            <style type="text/css"> <?php echo $internalStyle['code']; ?> </style>
        <?php else: ?>
            <link rel="stylesheet" href="<?php echo $internalStyle ?>">
        <?php endif; ?>
    <?php endforeach; ?>
    <!--[if lte IE 8]>
    <script src="/components/webtales/rubedo-frontoffice/legacyFixes/respond.js"></script>
    <![endif]-->
    <!--library scripts-->
    <script src="/components/jquery/jquery/jquery-1.11.1.min.js"></script>
    <script src="/components/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!--[if lte IE 9]>
    <script src="/components/webtales/rubedo-frontoffice/legacyFixes/angular.js"></script>
    <script src="/components/webtales/rubedo-frontoffice/legacyFixes/history.js"></script>
    <![endif]-->
    <![if !lte IE 9]>
    <script src="/components/angular/angular.js/angular.js"></script>
    <![endif]>
    <script src="/components/angular/angular.js/angular-route.js"></script>
<!--    <script src="/components/angular/angular.js/angular-cookies.js"></script>-->
    <script src="/components/angular/lrInfiniteScroll.js/lrInfiniteScroll.js"></script>
    <script src="/components/jquery/htmlClean/jquery.htmlClean.min.js"></script>
    <script src='/components/jquery/fullcalendar/lib/moment.min.js'></script>
    <script src='/components/jquery/fullcalendar/lib/jquery-ui.custom.min.js'></script>
    <script src='/components/jquery/fullcalendar/fullcalendar.min.js'></script>
    <script src='/components/jquery/fullcalendar/lang/en-gb.js'></script>
    <script src='/components/jquery/fullcalendar/lang/fr.js'></script>
    <script src='/components/OwlFonk/OwlCarousel/owl-carousel/owl.carousel.min.js'></script>
    <script src='/components/jakiestfu/Snap.js/snap.min.js'></script>
    <script src='/components/jtrussell/angular-snap.js-bower/angular-snap.min.js'></script>
    <script src='/components/vitalets/angular-xeditable/dist/js/xeditable.min.js'></script>
    <script src='/components/vitalets/angular-xeditable/libs/checklist-model.js'></script>
    <script src='/components/webtales/ckeditor/ckeditor.js'></script>
    <script src='/components/esvit/ng-ckeditor/ng-ckeditor.min.js'></script>
    <script src='//maps.googleapis.com/maps/api/js?sensor=true&libraries=places'></script>
    <script src='/components/lodash/lodash/dist/lodash.underscore.min.js'></script>
    <script src='/components/angular-ui/angular-google-maps/dist/angular-google-maps.js'></script>
    <script src="/components/longtailvideo/jwplayer/jwplayer.js"></script>
    <script src="/components/ivpusic/angular-cookie/angular-cookie.min.js"></script>
    <script src="//s7.addthis.com/js/300/addthis_widget.js"></script>
    <script src="/components/stowball/jQuery-rwdImageMaps/jquery.rwdImageMaps.min.js"></script>
    <script src="/components/webtales/rubedo-frontoffice/libraryOverrides/angular-google-map.js"></script>
    <?php if ($this->activateMagic): ?>
        <script src="/components/fingerprintjs/fingerprint.js"></script>
    <?php endif; ?>
    <?php if ($this->angularLocale): ?>
        <script src="/components/angular/angular.js/i18n/angular-locale_<?php echo $this->angularLocale; ?>.js"></script>
    <?php endif; ?>
    <!--frontoffice scripts-->
    <script src="/components/webtales/rubedo-frontoffice/src/modules/rubedoDataAccess/rubedoDataAccess.js"></script>
    <script src="/components/webtales/rubedo-frontoffice/src/modules/rubedoFields/rubedoFields.js"></script>
    <script src="/components/webtales/rubedo-frontoffice/src/modules/rubedoBlocks/rubedoBlocks.js"></script>
    <script src="/components/webtales/rubedo-frontoffice/src/modules/rubedo/rubedo.js"></script>
    <!--external resource scripts-->
    <?php foreach($this->siteResources['externalScripts'] as $externalScript): ?>
        <script src="<?php echo $externalScript['url']; ?>"></script>
    <?php endforeach; ?>
    <!--internal resource scripts-->
    <?php foreach($this->siteResources['internalScripts'] as $internalScript): ?>
        <?php if (is_array($internalScript)): ?>
            <script type="text/javascript"> <?php echo $internalScript['code']; ?> </script>
        <?php else: ?>
            <script type="text/javascript" src="<?php echo $internalScript; ?>"></script>
        <?php endif; ?>
    <?php endforeach; ?>
    <!--base href for angular routing-->
    <base href="/">
</head>
<body>
    <snap-drawer ng-if="rubedo.current.user.rights.canEdit" class="rubedo-admin-drawer">
        <ng-include src="'/components/webtales/rubedo-frontoffice/templates/admin/admin.html'"></ng-include>
    </snap-drawer>
    <snap-content snap-options="rubedo.snapOpts" class="rubedo-page-holder">
        <button ng-if="rubedo.current.user.rights.canEdit" ng-click="rubedo.toggleAdminPanel()" class="btn btn-default rubedo-admin-btn">
            <img alt="Admin" title="Admin" src="/components/webtales/rubedo-frontoffice/img/salamander.png">
        </button>
        <div ng-view></div>
    </snap-content>
    <ng-include src="'/components/webtales/rubedo-frontoffice/templates/modals.html'"></ng-include>

</body>
</html>