<!DOCTYPE html>
<html xmlns:ng="http://angularjs.org" id="ng-app" ng-app="rubedo" ng-controller="RubedoController as rubedo">
<head>
    <!--[if lte IE 8]>
    <script>
        document.createElement('ng-include');
        document.createElement('ng-repeat');
        document.createElement('ng-view');
        document.createElement('rubedo-block');
        document.createElement('rubedo-field');
        document.createElement('rubedo-notification');
        document.createElement('snap-drawer');
        document.createElement('snap-content');
        document.createElement('rubedo-custom-template');
    </script>
    <![endif]-->
    <meta charset="UTF-8">
    <meta name="fragment" content="!">
    <meta ng-if="rubedo.current.page.description" name="description"
          ng-attr-content="{{rubedo.current.page.description}}"/>
    <meta ng-if="rubedo.current.page.metaKeywords" name="keywords"
          ng-attr-content="{{ rubedo.current.page.metaKeywords }}">
    <meta ng-if="rubedo.current.page.metaRobots" name="robots" ng-attr-content="{{ rubedo.current.page.metaRobots }}">
    <meta ng-if="rubedo.current.page.metaAuthor" name="author" ng-attr-content="{{ rubedo.current.page.metaAuthor }}">

    <link ng-if="rubedo.current.page.contentCanonicalUrl" rel="canonical"
          ng-href="{{ rubedo.current.page.contentCanonicalUrl }}"/>
    <link rel="alternate" ng-repeat="alternate in rubedo.current.page.i18n" ng-href="{{alternate.fullUrl}}" hreflang="{{alternate.locale}}" />
    <!--mobile meta-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title ng-bind-template="{{rubedo.current.page.title}}"></title>
    <!--css-->
    <link rel="stylesheet" href="/components/jtrussell/angular-snap.js-bower/angular-snap-only.min.css">
    <link rel="stylesheet" href="/components/twbs/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/theme/<?php echo $this->siteTheme; ?>/css/rubedo.css">
    <link href='/components/jquery/fullCalendar/fullcalendar.css' rel='stylesheet'/>
    <link href='/components/jquery/fullCalendar/fullcalendar.print.css' rel='stylesheet' media='print'/>
    <link rel="stylesheet" href="/components/OwlFonk/OwlCarousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="/components/OwlFonk/OwlCarousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="/components/vitalets/angular-xeditable/dist/css/xeditable.css">
    <link rel="stylesheet" href="/components/dalelotts/angular-bootstrap-datetimepicker/src/css/datetimepicker.css">
    <!--external resource styles-->
    <?php foreach ($this->siteResources['externalStyles'] as $externalStyle): ?>
        <link rel="stylesheet" href="<?php echo $externalStyle['url']; ?>">
    <?php endforeach; ?>
    <!--internal resource styles-->
    <?php foreach ($this->siteResources['internalStyles'] as $internalStyle): ?>
        <?php if (is_array($internalStyle)): ?>
            <style type="text/css"> <?php echo $internalStyle['code']; ?> </style>
        <?php else: ?>
            <link rel="stylesheet" href="<?php echo $internalStyle ?>">
        <?php endif; ?>
    <?php endforeach; ?>
    <!--[if lte IE 8]>
    <script src="/theme/<?php echo $this->siteTheme; ?>/legacyFixes/respond.js"></script>
    <![endif]-->
    <!--library scripts-->
    <script src="/components/jquery/jquery/jquery-1.11.1.min.js"></script>
    <script src="/components/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <!--[if lte IE 9]>
    <script src="/theme/<?php echo $this->siteTheme; ?>/legacyFixes/angular.js"></script>
    <script src="/theme/<?php echo $this->siteTheme; ?>/legacyFixes/history.js"></script>
    <![endif]-->
    <![if !lte IE 9]>
    <script src="/components/angular/angular.js/angular.js"></script>
    <![endif]>
    <script src="/components/angular/angular.js/angular-route.js"></script>
    <script src="/components/angular/lrInfiniteScroll.js/lrInfiniteScroll.js"></script>
    <script src="/components/jquery/htmlClean/jquery.htmlClean.min.js"></script>
    <script src='/components/jakiestfu/Snap.js/snap.min.js'></script>
    <script src='/components/jtrussell/angular-snap.js-bower/angular-snap.min.js'></script>
    <script src='/components/vitalets/angular-xeditable/dist/js/xeditable.min.js'></script>
    <script src='/components/vitalets/angular-xeditable/libs/checklist-model.js'></script>
    <script src='/components/webtales/ckeditor/ckeditor.js'></script>
    <script src='/components/lemonde/angular-ckeditor/angular-ckeditor.min.js'></script>
    <script src='//maps.googleapis.com/maps/api/js?sensor=true&libraries=places'></script>
    <script src='/components/lodash/lodash/dist/lodash.underscore.min.js'></script>
    <script src='/components/angular-ui/angular-google-maps/dist/angular-google-maps.js'></script>
    <script src="/components/longtailvideo/jwplayer/jwplayer.js"></script>
    <script src="/components/ivpusic/angular-cookie/angular-cookie.min.js"></script>
    <script src="/components/ded/script.js/dist/script.min.js"></script>
    <script src="/theme/<?php echo $this->siteTheme; ?>/libraryOverrides/angular-google-map.js"></script>
    <script src="/theme/<?php echo $this->siteTheme; ?>/lib/toaster/jquery.toaster.js"></script>
    <script src="/theme/<?php echo $this->siteTheme; ?>/lib/angularStrap/ngStrap.js"></script>
    <script src="/components/jquery/fullCalendar/lib/moment.min.js"></script>
    <script src="/components/dalelotts/angular-bootstrap-datetimepicker/src/js/datetimepicker.js"></script>
    <?php if ($this->activateMagic): ?>
        <script src="/components/fingerprintjs/fingerprint.js"></script>
    <?php endif; ?>
    <?php if ($this->angularLocale): ?>
        <script
            src="/components/angular/angular.js/i18n/angular-locale_<?php echo $this->angularLocale; ?>.js"></script>
    <?php endif; ?>
    <!--internal angular modules scripts-->
    <?php if (isset($this->siteResources['angularModulesPaths'])) {
        foreach ($this->siteResources['angularModulesPaths'] as $angularModulePath): ?>
            <script type="text/javascript" src="<?php echo $angularModulePath; ?>"></script>
        <?php endforeach;
    } ?>
    <script type="text/javascript">
        window.rubedoConfig = {
            siteTheme: "<?php echo $this->siteTheme; ?>",
            extensionAngularModules:<?php if(isset($this->siteResources['angularModules'])){
            echo json_encode($this->siteResources['angularModules']);
            } else {
            echo 'false';
            } ?>
        };
    </script>

    <!--frontoffice scripts-->
    <script src="/theme/<?php echo $this->siteTheme; ?>/src/modules/rubedoDataAccess/rubedoDataAccess.js"></script>
    <script src="/theme/<?php echo $this->siteTheme; ?>/src/modules/rubedoFields/rubedoFields.js"></script>
    <script src="/theme/<?php echo $this->siteTheme; ?>/src/modules/rubedoBlocks/rubedoBlocks.js"></script>
    <script src="/theme/<?php echo $this->siteTheme; ?>/src/modules/rubedo/rubedo.js"></script>
    <!--external resource scripts-->
    <?php foreach ($this->siteResources['externalScripts'] as $externalScript): ?>
        <script src="<?php echo $externalScript['url']; ?>"></script>
    <?php endforeach; ?>
    <!--internal resource scripts-->
    <?php foreach ($this->siteResources['internalScripts'] as $internalScript): ?>
        <?php if (is_array($internalScript)): ?>
            <script type="text/javascript"> <?php echo $internalScript['code']; ?> </script>
        <?php else: ?>
            <script type="text/javascript" src="<?php echo $internalScript; ?>"></script>
        <?php endif; ?>
    <?php endforeach; ?>
    <!--base href for angular routing-->
    <base href="/">

    <!-- Script for google analytics -->
    <?php if ($this->googleAnalyticsKey): ?>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', '<?php echo $this->googleAnalyticsKey; ?>']);
            _gaq.push(['_trackPageview']);
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    <?php endif; ?>
</head>
<body ng-class="rubedo.current.page.pageProperties.bodyClass">
<snap-drawer ng-if="rubedo.current.user.rights.canEdit" class="rubedo-admin-drawer" style="display: none;">
    <ng-include src="rubedo.themePath+'/templates/admin/admin.html'"></ng-include>
</snap-drawer>
<div class="btn-group-vertical  rubedo-admin-btn" ng-if="rubedo.current.user.rights.canEdit">
    <button title="Admin" ng-click="rubedo.toggleAdminPanel()" class="btn btn-default">
        <span ng-class="rubedo.adminBtnIconClass"></span>
    </button>
    <button ng-click="rubedo.persistChanges()"
            class="btn btn-default"
            ng-if="rubedo.fieldEditMode&&rubedo.current.user.rights.canEdit"
            title="{{rubedo.translate('Edition.Label.SaveChanges','Save changes')}}">
        <span class="glyphicon glyphicon-ok"></span>
    </button>
    <button ng-click="rubedo.revertChanges()"
            class="btn btn-default"
            ng-if="rubedo.fieldEditMode&&rubedo.current.user.rights.canEdit"
            title="{{rubedo.translate('Edition.Label.DiscardChanges','Discard changes')}}">
        <span class="glyphicon glyphicon-remove"></span>
    </button>
</div>
<snap-content snap-options="rubedo.snapOpts" class="rubedo-page-holder">
    <div ng-view></div>
</snap-content>
</body>
</html>
