<?php

/**
 * Rubedo
*
* LICENSE
*
* yet to be written
* 
* This is the main front-office layout
*
* @category Rubedo
* @package Rubedo
* @copyright Copyright (c) 2012-2012 WebTales (http://www.webtales.fr)
* @license yet to be written
* @version $Id$
*/
?>
<!DOCTYPE html>
<html>
<head>
<title>Rubedo Installer</title>
<meta property="og:title" content="Rubedo">
<meta property="Content-Type" content="text/html; charset=UTF-8">
<?php

$this->headLink()
    ->prependStylesheet("/components/twitter/bootstrap/css/bootstrap-responsive.min.css", "screen")
    ->prependStylesheet("/components/twitter/bootstrap/css/bootstrap.min.css", "screen");
$this->headScript()
    ->appendFile("/components/jquery/jquery/jquery-1.9.1.min.js")
    ->appendFile("/components/twitter/bootstrap/js/bootstrap.min.js");

echo $this->headLink();
?>
</head>

<body
	style="background-image: url('/backoffice/resources/images/logo.png'); background-position: 50% 100px; background-repeat: no-repeat no-repeat; min-height: 800px;">
	<div class="navbar navbar-inverse">
		<div class="navbar-inner">
			<a class="brand"
				href="<?php echo $this->url(array('action'=>'index','module'=>'install'),null,true);?>">Rubedo
				Install Tool</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
                   <?php foreach ($this->navigationContainer as $page){?>
                       <li <?php if($page->isActive()){?> class="active"
						<?php }?>><a href="<?php echo $page->getHref();?>"><?php echo $page->getLabel();?></a>
					</li>
                   <?php } ?>
               </ul>
			</div>
			<!-- <ul class="nav">
				<li class="active">
					<a href="#">Home</a>
				</li>
				<li><a href="#">Link</a></li>
				<li><a href="#">Link</a></li>
			</ul> -->
		</div>
	</div>
	<div class="container">
		<div class="row-fluid" style="height: 150px;"></div>
		<div class="row-fluid">
			<div class="span2"></div>
			<div class="span8">
				<div class="well">
    				<?php echo $this->layout()->content?>
    				<div class='clearfix'></div>
    				<?php if($this->displayMode=='wizard'){?>
                        <ul class="pager">
                            <?php if($this->previous){?>
                        	<li class="previous"><a
							href="<?php echo $this->previous->getHref();?>">&larr; <?php echo $this->previous->getLabel();?></a></li>
                        	<?php }else{?>
                        	    <li class="previous"><a
							href="<?php echo $this->url(array('action'=>'start-wizard','module'=>'install'),null,true);?>">&larr;
								Intro</a></li>
                        	<?php } ?>
                        	
                        	<?php if($this->isReady){?>
                            	<?php if($this->next){?>
                            	<li class="next"><a
							href="<?php echo $this->next->getHref();?>"><?php echo $this->next->getLabel();?> &rarr;</a></li>
                            	<?php }else{?>
                            	    <li class="next"><a
							href="<?php echo $this->url(array('action'=>'finish-wizard','module'=>'install'),null,true);?>">Finish
								&rarr;</a></li>
                            	<?php } ?>
                        	<?php } ?>
                         </ul> 
                    <?php }?>
                        

				</div>
			</div>
		</div>
	</div>
	<?php echo $this->headScript(); ?>
	<script>
	var changed = false;
	$('#installForm').change(editionMode);
	$('#installForm').bind("reset", readMode);
	
	function editionMode(){
		changed = true;
		$(".pager > li").addClass('disabled');
		$(".pager > .disabled").click(function(e) {
			if(changed){
				e.preventDefault();
			}
		});
	}

	function readMode(){
		changed = false;
		$(".pager > li").removeClass('disabled');
	}
		
	</script>

</body>
</html>