<!DOCTYPE html>
<html>
<head>
<title>Rubedo Installer</title>
<meta property="og:title" content="Install Rubedo">
<meta property="Content-Type" content="text/html; charset=UTF-8">
<?php

$this->headLink()
    ->prependStylesheet("/css/bootstrap-responsive.css", "screen")
    ->prependStylesheet("/css/bootstrap.css", "screen");
$this->headScript()->appendFile("/templates/root/js/jquery.js");

echo $this->headLink();
?>
</head>

<body
	style="background-image: url(http://rubedo.localhost/backoffice/resources/images/logo.png); background-position: 50% 50%; background-repeat: no-repeat no-repeat; min-height: 800px;">
	<div class="container">
		<div class="row-fluid" style="height: 250px;"></div>
		<div class="row-fluid">
			<div class="span2"></div>
			<div class="span8">
				<div class="well">
    				<?php echo $this->layout()->content?>
    				<div class='clearfix'></div>
				</div>
			</div>
		</div>
	</div>
	<?php echo $this->headScript(); ?>
		
</body>
</html>