<div class="alert alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Error!</strong> You cannot access to back-office.
</div>
<a class="btn btn-large btn-primary" type="button" href="/<?php echo $this->baseUrl();?>"><i class="icon-home icon-white"></i> Front Office</a>
<a class="btn btn-large btn-danger" type="button" href="<?php echo $this->url(array('action'=>'index'));?>"><i class="icon-off icon-white"></i> Log Out</a>

