<!DOCTYPE html>
<html>
<head>
    <title>Rubedo Installer</title>
    <meta property="og:title" content="Rubedo">
    <meta property="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <?php
    $this->headLink()
        ->prependStylesheet("/components/twbs/bootstrap/dist/css/bootstrap.min.css");
    $this->headScript()
        ->appendFile("/components/jquery/jquery/jquery-1.11.1.min.js")
        ->appendFile("/components/twbs/bootstrap/dist/js/bootstrap.min.js");

    echo $this->headLink();

    $children = $this->viewModel()
        ->getCurrent()
        ->getChildren();
    $child = $children[0];
    $view = $child->getVariables();
    ?>
</head>

<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#install-menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"
               href="<?php echo $this->url(null, array(), array('action' => 'index')); ?>">Rubedo
                Install Tool</a>
        </div>
        <?php if ((isset($view['displayMode']) && $view['displayMode'] != 'wizard' && $view['displayMode'] != 'start-wizard') || !isset($view['displayMode'])) { ?>
            <div class="collapse navbar-collapse" id="install-menu">
                <ul class="nav navbar-nav">
                    <?php if (isset($view['navigationContainer'])) { ?>
                        <?php foreach ($view['navigationContainer'] as $page) { ?>
                            <li <?php if ($page->isActive()) { ?> class="active"
                            <?php } ?>><a href="<?php echo $page->getHref(); ?>"><?php echo $page->getLabel(); ?></a>
                            </li>
                        <?php
                        }
                    } ?>
                </ul>
            </div>
        <?php } ?>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-12" style="padding-top: 75px">
            <div class="well">
                <?php echo $this->content; ?>
                <div class='clearfix'></div>
                <?php if (isset($view['displayMode']) && $view['displayMode'] == 'wizard') { ?>
                    <ul class="pager">
                        <?php if (isset($view['previous'])) { ?>
                            <li class="previous"><a
                                    href="<?php echo $view['previous']->getHref(); ?>">&larr; <?php echo $view['previous']->getLabel(); ?></a>
                            </li>
                        <?php } else { ?>
                            <li class="previous"><a
                                    href="<?php echo $this->url('install', array('controller' => 'index', 'action' => 'start-wizard', 'module' => 'install'), null, true); ?>">&larr;
                                    Intro</a></li>
                        <?php } ?>
                        <?php if ($view['isReady']) { ?>
                            <?php if (isset($view['next'])) { ?>
                                <li class="next"><a
                                        href="<?php echo $view['next']->getHref(); ?>"><?php echo $view['next']->getLabel(); ?> &rarr;</a>
                                </li>
                            <?php } else { ?>
                                <li class="next"><a
                                        href="<?php echo $this->url('install', array('controller' => 'index', 'action' => 'finish-wizard', 'module' => 'install'), null, true); ?>">Finish
                                        &rarr;</a></li>
                            <?php } ?>
                        <?php } ?>
                    </ul>
                <?php } ?>


            </div>
        </div>
    </div>
</div>
<?php echo $this->headScript(); ?>
<script>
    var changed = false;
    $('#installForm').change(editionMode);
    $('#installForm').bind("reset", readMode);

    function editionMode() {
        changed = true;
        $(".pager > li").addClass('disabled');
        $(".pager > .disabled").click(function (e) {
            if (changed) {
                e.preventDefault();
            }
        });
    }

    function readMode() {
        changed = false;
        $(".pager > li").removeClass('disabled');
    }
</script>
</body>
</html>