<h1>Create Groups and Users</h1>
<br />
<div id="alerts">
    <?php if($this->hasError){?>
    <div class="alert alert-error"><?php echo $this->errorMsgs;?></div>
    <?php }?>
    <?php if($this->isCreated){?>
    <div class="alert alert-success">Groups & Users Created</div>
    <?php }?>
    
</div>

<div class="row-fluid">
    <?php if(!$this->isCreated){?>
	<a
		href="<?php echo $this->url(array('doCreateGroups'=>'1','controller'=>'data-test','action'=>'index','module'=>'install'),null,true);?>"
		class="btn btn-large btn-primary" type="button"><i
		class="icon-tasks icon-white"></i> Run</a>

    <?php }else{ ?>
    <a
		href="<?php echo $this->url(array('controller'=>'data-test','action'=>'index','module'=>'install'),null,true);?>"
		class="btn btn-large btn-primary" type="button"><i
		class="icon-home icon-white"></i> Return</a>
    <?php }?>
	
</div>