<div class="hero-unit">
	<h1>Installation of Rubedo</h1>
	<p>Configuration Wizard had been run.</p>
	<p>
		<a
			href="<?php echo $this->url(array('module'=>'backoffice','action'=>'index','controller'=>'login'),null,true);?>"
			class="btn btn-large btn-success" type="button"><i
			class="icon-user icon-white"></i> Access to Back Office</a> 
		<a
			href="<?php echo $this->url(array('module'=>'install','action'=>'start-wizard','controller'=>'index'),null,true);?>"
			class="btn btn-large btn-danger" type="button"><i
			class="icon-wrench icon-white"></i> Run wizard again</a>
	</p>
</div>