<h1>Elastic Search Configuration</h1>
<p>An Elastic Search server is required to run Rubedo. <a href="http://www.elasticsearch.org">See www.elasticsearch.org</a> if needed.</p>
<p>Two indexes are used, one for contents and one for digital documents.</p>
<p>This tool cannot do not manage securing access to Elastic Search, protections should be set by Elastic Serach Administrator</p>
<br />
<div id="alerts">
    <?php if($this->hasError){?>
    <div class="alert alert-error"><?php echo $this->errorMsgs;?></div>
    <?php }?>
    <?php if($this->isReady){?>
    <div class="alert alert-success">Connection to ES is set</div>
    <?php }?>
</div>
<?php echo $this->form->render();?>