<h1>DataBase Configuration</h1>
<br />

<?php if($this->displayMode=='wizard'){?>
<ul class="pager">
	<li class="previous"><a
		href="<?php echo $this->url(array('action'=>'start-wizard'));?>">&larr;
			Intro</a></li>
  <?php if($this->isReady){?>
  <li class="next"><a
		href="<?php echo $this->url(array('action'=>'set-admin'));?>">Admin
			Account &rarr;</a></li>
  <?php }?>
</ul>
<?php }else{?>
<div class='pull-right'><a href="<?php echo $this->url(array('action'=>'index'));?>" class="btn btn-large btn-primary" type="button"><i class="icon-home"></i> Return</a></div>
<?php }?>