<h1>Local Domain Override</h1>
<br />
<div id="alerts">
    <?php if($this->hasError){?>
    <div class="alert alert-error"><?php echo $this->errorMsgs;?></div>
    <?php }?>
    
    
</div>

<?php if(count($this->overrideList)){?>
<div class="well">
	<h2>Defined Override</h2>
	<ul>
   <?php foreach ($this->overrideList as $domain => $localDomain){?>
   <li><?php echo $this->escape($domain);?> => <?php echo $this->escape($localDomain);?></li>
   <?php }?>
</ul>
</div>
<?php }?>

<h2>Add local override</h2>
<?php echo $this->form->render();?>
