<!DOCTYPE html>

<!-- Auto Generated with Sencha Architect -->
<!-- Modifications to this file will be overwritten. -->
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Rubedo</title>

<link rel="stylesheet"
	href="<?php echo $this->baseUrl();?>/components/sencha/extjs/resources/css/ext-all-gray.css"
	id="ext_theme">
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/backoffice/resources/css/red_theme.css" id="maintheme">


<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/backoffice/resources/boxselect/BoxSelect.css">
<link rel="stylesheet"
	href="<?php echo $this->baseUrl();?>/backoffice/resources/ratingField/Ext.ux.widget.Rating.css"
	id="ratingFieldCSS">

<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/backoffice/resources/css/data-view.css"
	id="dataViewUX">

<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/backoffice/resources/css/uxs.css">

<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/backoffice/resources/ux/container/ButtonSegment.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/backoffice/resources/ux/grid/feature/Tileview.css">

</head>
<body
	style="background-image: url('<?php echo $this->baseUrl();?>/backoffice/resources/images/logo.png'); background-position: 50% 100px; background-repeat: no-repeat no-repeat;">
	<script
		src="<?php echo $this->baseUrl();?>/components/sencha/extjs/ext-all-debug.js"></script>
	<script
		src="<?php echo $this->baseUrl();?>/components/sencha/extjs/locale/ext-lang-fr.js"
		id="locale"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/boxselect/BoxSelect.js"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/ratingField/Ext.ux.widget.Rating.js"
		id="ratingFieldJS"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/ColorField.js" id="Ext.ux.ColorFieldJS"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/FilterBar.js"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/ClearButton.js"></script>
	<script src="/components/webtales/ckeditor/ckeditor.js"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/plupload/js/plupload.js"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/plupload/js/plupload.html4.js"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/plupload/js/plupload.html5.js"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/plupload/js/plupload.flash.js"></script>
	<script src="<?php echo $this->baseUrl();?>/backoffice/resources/plupload/js/plupload.silverlight.js"></script>
	<script type="text/javascript" src="app.js?_dc=1361290173305"></script>
</body>
</html>