<?php
use Zend\Form\Element\Captcha;

$element = $this->element;

$messages = $element->getMessages();
$hasError = !empty($messages);
$classError = $hasError ? 'error' : '';
echo '<div class="form-group ' . $classError . '">';
echo '<div class="col-sm-2 control-label">';
echo $this->FormLabel($element);
echo '</div>';
echo '<div class="col-sm-10">';
if ($element instanceof Captcha) {
    $helperName = $element->getCaptcha()->getHelperName();
    $helper = $this->plugin($helperName);
    if ($helper instanceof Zend\Form\View\Helper\Captcha\Image) {
        $helper->setSeparator('<br/><br/>');
        $helper->setCaptchaPosition(Zend\Form\View\Helper\Captcha\Image::CAPTCHA_PREPEND);
    }
    echo $this->plugin($helperName)->render($element);
} else {
    echo $this->FormElement()->render($element);
}

echo $this->FormElementErrors()
    ->setMessageOpenFormat('<div class="help-inline">')
    ->setMessageSeparatorString('</div><div class="help-inline">')
    ->setMessageCloseString('</div>')
    ->render($element);
echo '</div>';

echo '</div>';