<?php
$element = $this->element;

$messages = $element->getMessages();
$hasError = ! empty($messages);
$classError = $hasError ? 'error' : '';
echo '<div class="control-group ' . $classError . '">';
echo '<div>';
echo $this->FormLabel($element);
echo '</div>';
echo '<div class="controls">';
echo $this->FormElement()->render($element);
echo $this->FormElementErrors()
    ->setMessageOpenFormat('<div class="help-inline">')
    ->setMessageSeparatorString('</div><div class="help-inline">')
    ->setMessageCloseString('</div>')
    ->render($element);
echo '</div>';

echo '</div>';