<?php
$element = $this->element;

if ($element->getName() == 'buttonGroup') {
    echo '<div class="form-actions">';
    echo $this->formCollection()->render($element);
    echo '</div>';
} else {
    echo '<fieldset>';
    $legend = $element->getAttribute('legend');
    if($legend){
        echo '<legend>'.$legend.'</legend>';
    }
    foreach ($element as $subElements) {
        
        //getAttribute
        if ($subElements instanceof Zend\Form\FieldsetInterface) {
            echo $this->partial('rubedo/install/controller/index/fieldset', array(
                'element' => $subElements
            )); 
        }
        
        else{
            echo $this->partial('rubedo/install/controller/index/element', array(
                'element' => $subElements
            ));
        }
        
    }
    echo '</fieldset>';
}