<?php //form.phtml
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
foreach ($form as $element) {
    
    if ($element instanceof Zend\Form\FieldsetInterface) {
        echo '<div class="form-actions">';
        echo $this->formCollection()->render($element);
        echo '</div>';
    } else {
        $messages = $element->getMessages();
        $hasError = !empty($messages);
        $classError = $hasError?'error':'';
        echo '<div class="control-group '.$classError.'">';
        echo '<div>';
        echo $this->FormLabel($element);
        echo '</div>';
        echo '<div class="controls">';
        echo $this->FormElement()->render($element);
        echo $this->FormElementErrors()->setMessageOpenFormat('<div class="help-inline">')
                ->setMessageSeparatorString('</div><div class="help-inline">')
                ->setMessageCloseString('</div>')->render($element);
        echo '</div>';
        
        echo '</div>';
    }
}

echo $this->form()->closeTag($form);
//echo $this->form()->render($form);