<?php 
//form.phtml
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
foreach ($form as $element) {
    
if ($element instanceof Zend\Form\FieldsetInterface) {
        if ($element->getName() == 'buttonGroup') {
            echo '<div class="form-actions">';
            echo $this->formCollection()->render($element);
            echo '</div>';
        } else {
            foreach ($element as $subElements){
                echo $this->partial('rubedo/install/controller/index/element', array(
                    'element' => $subElements
                ));
            }
            
        }
    } else {
        echo $this->partial('rubedo/install/controller/index/element', array(
            'element' => $element
        ));
    }
}

echo $this->form()->closeTag($form);
//echo $this->form()->render($form);