<h1>Accounts</h1>
<p>Create admin accounts to log in the backoffice.</p>

<br />
<div id="alerts">
    <?php if($this->hasError){?>
    <div class="alert alert-error"><?php echo $this->form->getErrorMessages();?></div>
    <?php }?>
    <?php if($this->hasAdmin){?>
    <div class="alert alert-success">
		Admin accounts exist :
		<ul>
            <?php foreach($this->adminAccounts as $admin){?>
            <li><?php echo $admin['login'].' - '.$admin['email'];?></li>
            <?php }?>
        </ul>
	</div>
    <?php }else{?>
    <div class="alert alert-error">No Admin Account Set</div>
    <?php }?>
    <?php if($this->creationDone){?>
    <div class="alert alert-success">Account created : <?php echo $this->accountName;?></div>
    <?php }else{?>
    <?php echo $this->form->render();?>
    <?php }?>
</div>